--------------------------------------------------------
--  DDL for Sequence ASSOCIATE_ID_SEQUENCE
--------------------------------------------------------
DROP TABLE IF EXISTS CALIBER_ASSOCIATE;
CREATE TABLE IF NOT EXISTS CALIBER_ASSOCIATE (ASSOCIATE_ID INT(11) PRIMARY KEY,ASSOCIATE_FIRST_NAME VARCHAR(256) NOT NULL,ASSOCIATE_LAST_NAME VARCHAR(256) NOT NULL,MARKETING_STATUS_ID INT(11),CLIENT_ID INT(11),END_CLIENT_ID INT(11),BATCH_ID INT(11));
DROP SEQUENCE IF EXISTS ASSOCIATE_ID_SEQUENCE;
CREATE SEQUENCE  IF NOT EXISTS  ASSOCIATE_ID_SEQUENCE  MINVALUE 5600  INCREMENT BY 1 START WITH 5600;



--------------------------------------------------------
--  File created - Thursday-March-26-2018   
--------------------------------------------------------
Insert into CALIBER_ASSOCIATE (ASSOCIATE_ID,ASSOCIATE_FIRST_NAME,ASSOCIATE_LAST_NAME,MARKETING_STATUS_ID,CLIENT_ID,END_CLIENT_ID,BATCH_ID) values (212,'Christopher','Oler',7,null,null,30);
Insert into CALIBER_ASSOCIATE (ASSOCIATE_ID,ASSOCIATE_FIRST_NAME,ASSOCIATE_LAST_NAME,MARKETING_STATUS_ID,CLIENT_ID,END_CLIENT_ID,BATCH_ID) values (213,'Emile','Paul',7,null,null,30);
Insert into CALIBER_ASSOCIATE (ASSOCIATE_ID,ASSOCIATE_FIRST_NAME,ASSOCIATE_LAST_NAME,MARKETING_STATUS_ID,CLIENT_ID,END_CLIENT_ID,BATCH_ID) values (214,'Okwong','Bassey',7,null,null,32);
Insert into CALIBER_ASSOCIATE (ASSOCIATE_ID,ASSOCIATE_FIRST_NAME,ASSOCIATE_LAST_NAME,MARKETING_STATUS_ID,CLIENT_ID,END_CLIENT_ID,BATCH_ID) values (215,'Jaime','Gonzalez',7,null,null,32);
Insert into CALIBER_ASSOCIATE (ASSOCIATE_ID,ASSOCIATE_FIRST_NAME,ASSOCIATE_LAST_NAME,MARKETING_STATUS_ID,CLIENT_ID,END_CLIENT_ID,BATCH_ID) values (216,'Amauris','Ferreira',7,null,null,32);
Insert into CALIBER_ASSOCIATE (ASSOCIATE_ID,ASSOCIATE_FIRST_NAME,ASSOCIATE_LAST_NAME,MARKETING_STATUS_ID,CLIENT_ID,END_CLIENT_ID,BATCH_ID) values (217,'Leon','Moore',7,null,null,32);
Insert into CALIBER_ASSOCIATE (ASSOCIATE_ID,ASSOCIATE_FIRST_NAME,ASSOCIATE_LAST_NAME,MARKETING_STATUS_ID,CLIENT_ID,END_CLIENT_ID,BATCH_ID) values (218,'AchIntegerya','Goel',7,null,null,32);
Insert into CALIBER_ASSOCIATE (ASSOCIATE_ID,ASSOCIATE_FIRST_NAME,ASSOCIATE_LAST_NAME,MARKETING_STATUS_ID,CLIENT_ID,END_CLIENT_ID,BATCH_ID) values (219,'Lenny','Lopez',7,null,null,32);
Insert into CALIBER_ASSOCIATE (ASSOCIATE_ID,ASSOCIATE_FIRST_NAME,ASSOCIATE_LAST_NAME,MARKETING_STATUS_ID,CLIENT_ID,END_CLIENT_ID,BATCH_ID) values (220,'Anthony','Ramoslebron',7,null,null,32);
Insert into CALIBER_ASSOCIATE (ASSOCIATE_ID,ASSOCIATE_FIRST_NAME,ASSOCIATE_LAST_NAME,MARKETING_STATUS_ID,CLIENT_ID,END_CLIENT_ID,BATCH_ID) values (221,'William','Humphries',7,null,null,32);
Insert into CALIBER_ASSOCIATE (ASSOCIATE_ID,ASSOCIATE_FIRST_NAME,ASSOCIATE_LAST_NAME,MARKETING_STATUS_ID,CLIENT_ID,END_CLIENT_ID,BATCH_ID) values (222,'Gregory','Lonsdale',7,null,null,32);
Insert into CALIBER_ASSOCIATE (ASSOCIATE_ID,ASSOCIATE_FIRST_NAME,ASSOCIATE_LAST_NAME,MARKETING_STATUS_ID,CLIENT_ID,END_CLIENT_ID,BATCH_ID) values (223,'Nickalas','Light',10,null,null,32);
Insert into CALIBER_ASSOCIATE (ASSOCIATE_ID,ASSOCIATE_FIRST_NAME,ASSOCIATE_LAST_NAME,MARKETING_STATUS_ID,CLIENT_ID,END_CLIENT_ID,BATCH_ID) values (224,'Jeremiah','Matthews',7,null,null,32);
Insert into CALIBER_ASSOCIATE (ASSOCIATE_ID,ASSOCIATE_FIRST_NAME,ASSOCIATE_LAST_NAME,MARKETING_STATUS_ID,CLIENT_ID,END_CLIENT_ID,BATCH_ID) values (225,'Jacob','Burton',7,null,null,32);
Insert into CALIBER_ASSOCIATE (ASSOCIATE_ID,ASSOCIATE_FIRST_NAME,ASSOCIATE_LAST_NAME,MARKETING_STATUS_ID,CLIENT_ID,END_CLIENT_ID,BATCH_ID) values (226,'Anthony','Oscovitch',7,null,null,32);
Insert into CALIBER_ASSOCIATE (ASSOCIATE_ID,ASSOCIATE_FIRST_NAME,ASSOCIATE_LAST_NAME,MARKETING_STATUS_ID,CLIENT_ID,END_CLIENT_ID,BATCH_ID) values (227,'James','Kim',7,null,null,32);
Insert into CALIBER_ASSOCIATE (ASSOCIATE_ID,ASSOCIATE_FIRST_NAME,ASSOCIATE_LAST_NAME,MARKETING_STATUS_ID,CLIENT_ID,END_CLIENT_ID,BATCH_ID) values (228,'Tyler','Bourque',7,null,null,32);
Insert into CALIBER_ASSOCIATE (ASSOCIATE_ID,ASSOCIATE_FIRST_NAME,ASSOCIATE_LAST_NAME,MARKETING_STATUS_ID,CLIENT_ID,END_CLIENT_ID,BATCH_ID) values (229,'Justin','Terasaka',7,null,null,32);
Insert into CALIBER_ASSOCIATE (ASSOCIATE_ID,ASSOCIATE_FIRST_NAME,ASSOCIATE_LAST_NAME,MARKETING_STATUS_ID,CLIENT_ID,END_CLIENT_ID,BATCH_ID) values (230,'Christopher','Lewis',10,null,null,32);
Insert into CALIBER_ASSOCIATE (ASSOCIATE_ID,ASSOCIATE_FIRST_NAME,ASSOCIATE_LAST_NAME,MARKETING_STATUS_ID,CLIENT_ID,END_CLIENT_ID,BATCH_ID) values (231,'Hunter','Heard',6,null,null,36);
Insert into CALIBER_ASSOCIATE (ASSOCIATE_ID,ASSOCIATE_FIRST_NAME,ASSOCIATE_LAST_NAME,MARKETING_STATUS_ID,CLIENT_ID,END_CLIENT_ID,BATCH_ID) values (232,'Daniel','Kaczmarczyk',6,null,null,36);
Insert into CALIBER_ASSOCIATE (ASSOCIATE_ID,ASSOCIATE_FIRST_NAME,ASSOCIATE_LAST_NAME,MARKETING_STATUS_ID,CLIENT_ID,END_CLIENT_ID,BATCH_ID) values (233,'Peter','Thompson',6,1,null,36);
Insert into CALIBER_ASSOCIATE (ASSOCIATE_ID,ASSOCIATE_FIRST_NAME,ASSOCIATE_LAST_NAME,MARKETING_STATUS_ID,CLIENT_ID,END_CLIENT_ID,BATCH_ID) values (234,'Joseph','AbiJaoudi',6,null,null,36);
Insert into CALIBER_ASSOCIATE (ASSOCIATE_ID,ASSOCIATE_FIRST_NAME,ASSOCIATE_LAST_NAME,MARKETING_STATUS_ID,CLIENT_ID,END_CLIENT_ID,BATCH_ID) values (235,'Andrew','Day',6,null,null,36);
Insert into CALIBER_ASSOCIATE (ASSOCIATE_ID,ASSOCIATE_FIRST_NAME,ASSOCIATE_LAST_NAME,MARKETING_STATUS_ID,CLIENT_ID,END_CLIENT_ID,BATCH_ID) values (236,'Alex','Gorring',6,null,null,36);
Insert into CALIBER_ASSOCIATE (ASSOCIATE_ID,ASSOCIATE_FIRST_NAME,ASSOCIATE_LAST_NAME,MARKETING_STATUS_ID,CLIENT_ID,END_CLIENT_ID,BATCH_ID) values (237,'Lea','Reambonanza',6,null,null,36);
Insert into CALIBER_ASSOCIATE (ASSOCIATE_ID,ASSOCIATE_FIRST_NAME,ASSOCIATE_LAST_NAME,MARKETING_STATUS_ID,CLIENT_ID,END_CLIENT_ID,BATCH_ID) values (238,'Robert','Kasprzyk',6,null,null,36);
Insert into CALIBER_ASSOCIATE (ASSOCIATE_ID,ASSOCIATE_FIRST_NAME,ASSOCIATE_LAST_NAME,MARKETING_STATUS_ID,CLIENT_ID,END_CLIENT_ID,BATCH_ID) values (239,'Titus','Kim',6,null,null,36);
Insert into CALIBER_ASSOCIATE (ASSOCIATE_ID,ASSOCIATE_FIRST_NAME,ASSOCIATE_LAST_NAME,MARKETING_STATUS_ID,CLIENT_ID,END_CLIENT_ID,BATCH_ID) values (240,'Andrew','Lang',6,null,null,36);
Insert into CALIBER_ASSOCIATE (ASSOCIATE_ID,ASSOCIATE_FIRST_NAME,ASSOCIATE_LAST_NAME,MARKETING_STATUS_ID,CLIENT_ID,END_CLIENT_ID,BATCH_ID) values (241,'Max','Bisesi',6,null,null,36);
Insert into CALIBER_ASSOCIATE (ASSOCIATE_ID,ASSOCIATE_FIRST_NAME,ASSOCIATE_LAST_NAME,MARKETING_STATUS_ID,CLIENT_ID,END_CLIENT_ID,BATCH_ID) values (242,'Richard','Camara',6,null,null,36);
Insert into CALIBER_ASSOCIATE (ASSOCIATE_ID,ASSOCIATE_FIRST_NAME,ASSOCIATE_LAST_NAME,MARKETING_STATUS_ID,CLIENT_ID,END_CLIENT_ID,BATCH_ID) values (243,'Tanner','Robinaugh',6,null,null,36);
Insert into CALIBER_ASSOCIATE (ASSOCIATE_ID,ASSOCIATE_FIRST_NAME,ASSOCIATE_LAST_NAME,MARKETING_STATUS_ID,CLIENT_ID,END_CLIENT_ID,BATCH_ID) values (244,'Jeff','Neufer',6,null,null,36);
Insert into CALIBER_ASSOCIATE (ASSOCIATE_ID,ASSOCIATE_FIRST_NAME,ASSOCIATE_LAST_NAME,MARKETING_STATUS_ID,CLIENT_ID,END_CLIENT_ID,BATCH_ID) values (245,'Leo','Stewart',6,null,null,36);
Insert into CALIBER_ASSOCIATE (ASSOCIATE_ID,ASSOCIATE_FIRST_NAME,ASSOCIATE_LAST_NAME,MARKETING_STATUS_ID,CLIENT_ID,END_CLIENT_ID,BATCH_ID) values (246,'Muhamed','Basic',6,null,null,36);
Insert into CALIBER_ASSOCIATE (ASSOCIATE_ID,ASSOCIATE_FIRST_NAME,ASSOCIATE_LAST_NAME,MARKETING_STATUS_ID,CLIENT_ID,END_CLIENT_ID,BATCH_ID) values (247,'Duc','Nguyen',6,null,null,36);
Insert into CALIBER_ASSOCIATE (ASSOCIATE_ID,ASSOCIATE_FIRST_NAME,ASSOCIATE_LAST_NAME,MARKETING_STATUS_ID,CLIENT_ID,END_CLIENT_ID,BATCH_ID) values (248,'Danielle','Williams',6,null,null,36);
Insert into CALIBER_ASSOCIATE (ASSOCIATE_ID,ASSOCIATE_FIRST_NAME,ASSOCIATE_LAST_NAME,MARKETING_STATUS_ID,CLIENT_ID,END_CLIENT_ID,BATCH_ID) values (249,'Yang','Lu',6,null,null,36);
Insert into CALIBER_ASSOCIATE (ASSOCIATE_ID,ASSOCIATE_FIRST_NAME,ASSOCIATE_LAST_NAME,MARKETING_STATUS_ID,CLIENT_ID,END_CLIENT_ID,BATCH_ID) values (250,'Michelle','Cominotto',6,null,null,36);
Insert into CALIBER_ASSOCIATE (ASSOCIATE_ID,ASSOCIATE_FIRST_NAME,ASSOCIATE_LAST_NAME,MARKETING_STATUS_ID,CLIENT_ID,END_CLIENT_ID,BATCH_ID) values (251,'Wesley','DeLoach',6,null,null,36);
Insert into CALIBER_ASSOCIATE (ASSOCIATE_ID,ASSOCIATE_FIRST_NAME,ASSOCIATE_LAST_NAME,MARKETING_STATUS_ID,CLIENT_ID,END_CLIENT_ID,BATCH_ID) values (252,'Christopher','Kaczenski',6,null,null,36);
Insert into CALIBER_ASSOCIATE (ASSOCIATE_ID,ASSOCIATE_FIRST_NAME,ASSOCIATE_LAST_NAME,MARKETING_STATUS_ID,CLIENT_ID,END_CLIENT_ID,BATCH_ID) values (253,'Grant','Arras',6,null,null,36);
Insert into CALIBER_ASSOCIATE (ASSOCIATE_ID,ASSOCIATE_FIRST_NAME,ASSOCIATE_LAST_NAME,MARKETING_STATUS_ID,CLIENT_ID,END_CLIENT_ID,BATCH_ID) values (254,'Mynhung','Pham',1,8,null,37);
Insert into CALIBER_ASSOCIATE (ASSOCIATE_ID,ASSOCIATE_FIRST_NAME,ASSOCIATE_LAST_NAME,MARKETING_STATUS_ID,CLIENT_ID,END_CLIENT_ID,BATCH_ID) values (255,'Anahi','Garnelo',6,null,null,37);
Insert into CALIBER_ASSOCIATE (ASSOCIATE_ID,ASSOCIATE_FIRST_NAME,ASSOCIATE_LAST_NAME,MARKETING_STATUS_ID,CLIENT_ID,END_CLIENT_ID,BATCH_ID) values (256,'Janine','Lee',6,null,null,37);
Insert into CALIBER_ASSOCIATE (ASSOCIATE_ID,ASSOCIATE_FIRST_NAME,ASSOCIATE_LAST_NAME,MARKETING_STATUS_ID,CLIENT_ID,END_CLIENT_ID,BATCH_ID) values (257,'AnnMarie','Bemberry',6,null,null,37);
Insert into CALIBER_ASSOCIATE (ASSOCIATE_ID,ASSOCIATE_FIRST_NAME,ASSOCIATE_LAST_NAME,MARKETING_STATUS_ID,CLIENT_ID,END_CLIENT_ID,BATCH_ID) values (258,'Rebeca','Otero',6,null,null,37);
Insert into CALIBER_ASSOCIATE (ASSOCIATE_ID,ASSOCIATE_FIRST_NAME,ASSOCIATE_LAST_NAME,MARKETING_STATUS_ID,CLIENT_ID,END_CLIENT_ID,BATCH_ID) values (259,'Sabina','Haque',6,null,null,37);
Insert into CALIBER_ASSOCIATE (ASSOCIATE_ID,ASSOCIATE_FIRST_NAME,ASSOCIATE_LAST_NAME,MARKETING_STATUS_ID,CLIENT_ID,END_CLIENT_ID,BATCH_ID) values (260,'Victoria','Chen',6,null,null,37);
Insert into CALIBER_ASSOCIATE (ASSOCIATE_ID,ASSOCIATE_FIRST_NAME,ASSOCIATE_LAST_NAME,MARKETING_STATUS_ID,CLIENT_ID,END_CLIENT_ID,BATCH_ID) values (261,'Carolyn','Rehm',6,null,null,37);
Insert into CALIBER_ASSOCIATE (ASSOCIATE_ID,ASSOCIATE_FIRST_NAME,ASSOCIATE_LAST_NAME,MARKETING_STATUS_ID,CLIENT_ID,END_CLIENT_ID,BATCH_ID) values (262,'Adrian','Chavez',6,null,null,38);
Insert into CALIBER_ASSOCIATE (ASSOCIATE_ID,ASSOCIATE_FIRST_NAME,ASSOCIATE_LAST_NAME,MARKETING_STATUS_ID,CLIENT_ID,END_CLIENT_ID,BATCH_ID) values (263,'Abaynhe','Abitew',6,null,null,38);
Insert into CALIBER_ASSOCIATE (ASSOCIATE_ID,ASSOCIATE_FIRST_NAME,ASSOCIATE_LAST_NAME,MARKETING_STATUS_ID,CLIENT_ID,END_CLIENT_ID,BATCH_ID) values (264,'Kayci','Parcells',6,null,null,38);