--------------------------------------------------------
--  DDL for Sequence ASSOCIATE_ID_SEQUENCE
--------------------------------------------------------
--In case a table needs to be created. Commented out because it creates more problems than it solves.
DROP TABLE IF EXISTS CALIBER_ASSOCIATE;
CREATE TABLE IF NOT EXISTS CALIBER_ASSOCIATE (ASSOCIATE_ID INT(11) PRIMARY KEY,ASSOCIATE_FIRST_NAME VARCHAR(256) NOT NULL,ASSOCIATE_LAST_NAME VARCHAR(256) NOT NULL,MARKETING_STATUS_ID INT(11) NOT NULL,CLIENT_ID INT(11) NOT NULL,END_CLIENT_ID INT(11) NOT NULL,BATCH_ID INT(11) NOT NULL);
DROP SEQUENCE IF EXISTS ASSOCIATE_ID_SEQUENCE;
CREATE SEQUENCE  IF NOT EXISTS  ASSOCIATE_ID_SEQUENCE  MINVALUE 5600  INCREMENT BY 1 START WITH 5600;




Insert into CALIBER_ASSOCIATE (ASSOCIATE_ID,ASSOCIATE_FIRST_NAME,ASSOCIATE_LAST_NAME,MARKETING_STATUS_ID,CLIENT_ID,END_CLIENT_ID,BATCH_ID) values (1,'John','Flon',22,33,44,55);
Insert into CALIBER_ASSOCIATE (ASSOCIATE_ID,ASSOCIATE_FIRST_NAME,ASSOCIATE_LAST_NAME,MARKETING_STATUS_ID,CLIENT_ID,END_CLIENT_ID,BATCH_ID) values (2,'Ben','Toms',11,77,34,52);
Insert into CALIBER_ASSOCIATE (ASSOCIATE_ID,ASSOCIATE_FIRST_NAME,ASSOCIATE_LAST_NAME,MARKETING_STATUS_ID,CLIENT_ID,END_CLIENT_ID,BATCH_ID) values (3,'Eric','Holder',21,53,47,50);
Insert into CALIBER_ASSOCIATE (ASSOCIATE_ID,ASSOCIATE_FIRST_NAME,ASSOCIATE_LAST_NAME,MARKETING_STATUS_ID,CLIENT_ID,END_CLIENT_ID,BATCH_ID) values (4,'Dan','Henderson',92,383,484,595);
Insert into CALIBER_ASSOCIATE (ASSOCIATE_ID,ASSOCIATE_FIRST_NAME,ASSOCIATE_LAST_NAME,MARKETING_STATUS_ID,CLIENT_ID,END_CLIENT_ID,BATCH_ID) values (5,'Bob','Saget',220,333,144,855);
Insert into CALIBER_ASSOCIATE (ASSOCIATE_ID,ASSOCIATE_FIRST_NAME,ASSOCIATE_LAST_NAME,MARKETING_STATUS_ID,CLIENT_ID,END_CLIENT_ID,BATCH_ID) values (6,'Rob','Stein',227,303,444,525);